# -*- coding: utf-8 -*-
"""Task Manager 4.2py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KblEY1Gx6j4UEYY5W5gmhUkz5aNQjw9k
"""

# Section 4.1 - Manual Task Manager Implementation
# Course constraint: Week 3 formatting, Week 4–6 logic, Week 9 doctest format

def display_menu():
    """
    Display menu options - uses Week 3 print formatting

    >>> display_menu() # doctest: +SKIP
    1. Add task
    2. List tasks
    3. Remove task
    4. Quit
    """
    print("1. Add task")
    print("2. List tasks")
    print("3. Remove task")
    print("4. Quit")


def get_user_choice():
    """
    Get and validate user choice using Week 6-style input validation

    >>> True # doctest: +SKIP
    True
    """
    choice = input("Enter your choice (1-4): ")
    while choice not in ["1", "2", "3", "4"]:
        print("Invalid input. Please enter a number between 1 and 4.")
        choice = input("Enter your choice (1-4): ")
    return choice


def main():
    """
    Main program loop - follows Week 5 while loop patterns
    """
    task_list = []
    running = True

    while running:
        display_menu()
        choice = get_user_choice()

        if choice == "1":
            task = input("Enter a task: ")
            task_list.append(task)
            print(f"Task added: {task}")
        elif choice == "2":
            if len(task_list) == 0:
                print("No tasks available.")
            else:
                print("Your tasks:")
                # Iterate through the task_list and print each task with its index
                for i in range(len(task_list)):
                    print(f"{i + 1}. {task_list[i]}")
        elif choice == "3":
            if len(task_list) == 0:
                print("No tasks to remove.")
            else:
                print("Your tasks:")
                # Iterate through the task_list and print each task with its index for removal
                for i in range(len(task_list)):
                    print(f"{i + 1}. {task_list[i]}")
                remove_index = input("Enter the number of the task to remove: ")
                # Check if the input is a digit
                if remove_index.isdigit():
                    remove_index = int(remove_index)
                    # Check if the index is within the valid range
                    if 1 <= remove_index <= len(task_list):
                        # Remove the task at the specified index
                        removed = task_list.pop(remove_index - 1)
                        print(f"Removed task: {removed}")
                    else:
                        print("Invalid task number.")
                else:
                    print("Invalid input. Please enter a number.")
        elif choice == "4":
            print("Exiting Task Manager. Goodbye!")
            running = False


# Only run doctests when this script is not in interactive mode
if __name__ == "__main__":
    import doctest
    # doctest.testmod() is skipped as it requires user input, making it difficult to automate
    # For testing functions that require user input, consider using mocking libraries or alternative testing methods
    main()